networks:
  cassandra:
services:
  cassandra1:
    image: cassandra:4.1.5
    volumes:
      - ./jmxremote.password:/etc/cassandra/jmxremote.password
      - ./jmxremote.password:/etc/cassandra/jmxremote.access
      - ./data/cassandra1:/var/lib/cassandra
    container_name: cassandra1
    hostname: cassandra1
    networks:
      - cassandra
    ports:
      - "9042:9042"
      - "7199:7199"
    environment:
        CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
        CASSANDRA_CLUSTER_NAME: MyTestCluster
        CASSANDRA_DC: DC1
        CASSANDRA_RACK: RACK1
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 16
        LOCAL_JMX: "no"
  cassandra2:
    image: cassandra:4.1.5
    volumes:
      - ./jmxremote.password:/etc/cassandra/jmxremote.password
      - ./jmxremote.password:/etc/cassandra/jmxremote.access
      - ./data/cassandra2:/var/lib/cassandra
    container_name: cassandra2
    hostname: cassandra2
    networks:
      - cassandra
    ports:
      - "9043:9042"
      - "7200:7199"
    environment:
        CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
        CASSANDRA_CLUSTER_NAME: MyTestCluster
        CASSANDRA_DC: DC1
        CASSANDRA_RACK: RACK2
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 16
        LOCAL_JMX: "no"
    depends_on:
      cassandra1:
        condition: service_started
  cassandra3:
    image: cassandra:4.1.5
    volumes:
      - ./jmxremote.password:/etc/cassandra/jmxremote.password
      - ./jmxremote.password:/etc/cassandra/jmxremote.access
      - ./data/cassandra3:/var/lib/cassandra
    container_name: cassandra3
    hostname: cassandra3
    networks:
      - cassandra
    ports:
      - "9044:9042"
      - "7201:7199"
    environment:
        CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
        CASSANDRA_CLUSTER_NAME: MyTestCluster
        CASSANDRA_DC: DC1
        CASSANDRA_RACK: RACK3
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 16
        LOCAL_JMX: "no"
    depends_on:
      cassandra2:
        condition: service_started
  reaper:
    image: thelastpickle/cassandra-reaper:latest
    container_name: reaper
    hostname: reaper
    networks:
      - cassandra
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
        REAPER_JMX_AUTH_USERNAME: reaperUser
        REAPER_JMX_AUTH_PASSWORD: reaperPass
        CRYPTO_SYSTEM_PROPERTY_SECRET: CRYPTO_SECRET
        CRYPTO_SECRET: secret
    depends_on:
      cassandra1:
        condition: service_started
