networks:
  cassandra:
services:
  cassandra1:
    image: cassandra:4.1.5-configmods
    build: ./build/cassandra
    user: root
    volumes:
      - ./.data/cassandra1:/var/lib/cassandra
      - ./datastax-mcac-agent-0.3.5-4.1-beta1:/opt/mcac
      - ./config/cassandra/jmxremote.password:/etc/cassandra/jmxremote.password
      - ./config/cassandra/jmxremote.password:/etc/cassandra/jmxremote.access
      - ./config/datastax-mcac-agent-0.3.5-4.1-beta1/collectd.conf.tmpl:/opt/mcac/config/collectd.conf.tmpl
      - ./config/datastax-mcac-agent-0.3.5-4.1-beta1/metric-collector.yaml:/opt/mcac/config/metric-collector.yaml
    container_name: cassandra1
    cpu_shares: 4
    hostname: cassandra1
    networks:
      - cassandra
    ports:
      - '9042:9042'
      - '9103:9103'
    environment:
        CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
        CASSANDRA_CLUSTER_NAME: MyTestCluster
        CASSANDRA_DC: DC1
        CASSANDRA_RACK: RACK1
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 1
        LOCAL_JMX: "no"
        JVM_OPTS: "-javaagent:/opt/mcac/lib/datastax-mcac-agent.jar"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
      start_interval: 10s
  cassandra2:
    image: cassandra:4.1.5-configmods
    build: ./build/cassandra
    user: root
    volumes:
      - ./.data/cassandra2:/var/lib/cassandra
      - ./datastax-mcac-agent-0.3.5-4.1-beta1:/opt/mcac
      - ./config/cassandra/jmxremote.password:/etc/cassandra/jmxremote.password
      - ./config/cassandra/jmxremote.password:/etc/cassandra/jmxremote.access
      - ./config/datastax-mcac-agent-0.3.5-4.1-beta1/collectd.conf.tmpl:/opt/mcac/config/collectd.conf.tmpl
      - ./config/datastax-mcac-agent-0.3.5-4.1-beta1/metric-collector.yaml:/opt/mcac/config/metric-collector.yaml
    container_name: cassandra2
    cpu_shares: 4
    hostname: cassandra2
    networks:
      - cassandra
    ports:
      - '9124:9042'
    environment:
        CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
        CASSANDRA_CLUSTER_NAME: MyTestCluster
        CASSANDRA_DC: DC1
        CASSANDRA_RACK: RACK2
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 1
        LOCAL_JMX: "no"
        JVM_OPTS: "-javaagent:/opt/mcac/lib/datastax-mcac-agent.jar"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
      start_interval: 10s
    depends_on:
      cassandra1:
        condition: service_healthy
  cassandra3:
    image: cassandra:4.1.5-configmods
    build: ./build/cassandra
    user: root
    volumes:
      - ./.data/cassandra3:/var/lib/cassandra
      - ./datastax-mcac-agent-0.3.5-4.1-beta1:/opt/mcac
      - ./config/cassandra/jmxremote.password:/etc/cassandra/jmxremote.password
      - ./config/cassandra/jmxremote.password:/etc/cassandra/jmxremote.access
      - ./config/datastax-mcac-agent-0.3.5-4.1-beta1/collectd.conf.tmpl:/opt/mcac/config/collectd.conf.tmpl
      - ./config/datastax-mcac-agent-0.3.5-4.1-beta1/metric-collector.yaml:/opt/mcac/config/metric-collector.yaml
    container_name: cassandra3
    cpu_shares: 4
    hostname: cassandra3
    networks:
      - cassandra
    ports:
      - '9342:9042'
    environment:
        CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
        CASSANDRA_CLUSTER_NAME: MyTestCluster
        CASSANDRA_DC: DC1
        CASSANDRA_RACK: RACK3
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 1
        LOCAL_JMX: "no"
        JVM_OPTS: "-javaagent:/opt/mcac/lib/datastax-mcac-agent.jar"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
      start_interval: 10s
    depends_on:
      cassandra2:
        condition: service_healthy
  reaper:
    image: thelastpickle/cassandra-reaper:latest
    user: root
    container_name: reaper
    restart: unless-stopped
    cpu_shares: 3
    hostname: reaper
    networks:
      - cassandra
    ports:
      - '8080:8080'
    environment:
        REAPER_JMX_AUTH_USERNAME: reaperUser
        REAPER_JMX_AUTH_PASSWORD: reaperPass
        CRYPTO_SYSTEM_PROPERTY_SECRET: CRYPTO_SECRET
        CRYPTO_SECRET: secret
    depends_on:
      cassandra1:
        condition: service_healthy
      cassandra2:
        condition: service_healthy
      cassandra3:
        condition: service_healthy
  prometheus:
    image: "prom/prometheus"
    user: root
    container_name: prometheus
    cpu_shares: 2
    hostname: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=14d'
      - '--storage.tsdb.allow-overlapping-blocks'
    ports:
      - '9090:9090'
    networks:
      - cassandra
    volumes:
      - "./.data/prometheus:/prometheus"
      - "./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml"
      - "./config/prometheus/tg_mcac.json:/etc/prometheus/tg_mcac.json"
    depends_on:
      cassandra1:
        condition: service_healthy
      cassandra2:
        condition: service_healthy
      cassandra3:
        condition: service_healthy
  grafana:
    image: grafana/grafana-oss
    user: root
    container_name: grafana
    cpu_shares: 2
    hostname: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - cassandra
    environment:
      GF_INSTALL_PLUGINS: 'grafana-polystat-panel'
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    volumes:
      - './.data/grafana:/var/lib/grafana'
      - './config/grafana/prometheus-datasource.yaml:/etc/grafana/provisioning/datasources/prometheus-datasource.yaml'
      - './config/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml'
      - './config/grafana/dashboards:/var/lib/grafana/dashboards'
    depends_on:
      prometheus:
        condition: service_started