{
 "title": "Cache Metrics",
 "description": "https://cassandra.apache.org/doc/4.1/cassandra/operating/metrics.html",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cassandra_threadpools_activetasks,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Capacity",
   "type": "timeseries",
   "description": "Cache capacity in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_cache_capacity{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Entries",
   "type": "timeseries",
   "description": "Total number of cache entries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_cache_entries{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Size",
   "type": "timeseries",
   "description": "Total size of occupied cache, in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_cache_size{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "One Minute Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_cache_oneminutehitrate{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fifteen Minute Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_cache_fifteenminutehitrate{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Five Minute Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_cache_fiveminutehitrate{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Misses",
   "type": "timeseries",
   "description": "Total amount of misses over time",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_cache_misses_count{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}