{
 "title": "CommitLog Metrics",
 "description": "https://cassandra.apache.org/doc/4.1/cassandra/operating/metrics.html#commitlog-metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cassandra_commitlog_completedtasks,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Completed Tasks",
   "type": "timeseries",
   "description": "Total number of commit log messages written since [re]start.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_commitlog_completedtasks{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "timeseries",
   "description": "Number of commit log messages written but yet to be fsync’d.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_commitlog_pendingtasks{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CommitLog Size",
   "type": "timeseries",
   "description": "Current size, in bytes, used by all the commit log segments.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_commitlog_totalcommitlogsize{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting On Segment Allocation",
   "type": "timeseries",
   "description": "Time spent waiting for a CommitLogSegment to be allocated - under normal conditions this should be zero.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_commitlog_waitingonsegmentallocation{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting On Commit",
   "type": "timeseries",
   "description": "The time spent waiting on CL fsync; for Periodic this is only occurs when the sync is lagging its sync interva",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_commitlog_waitingoncommit{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}