{
 "title": "Compaction Metrics",
 "description": "https://cassandra.apache.org/doc/4.1/cassandra/operating/metrics.html#compaction-metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cassandra_compaction_completedtasks,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes Compacted",
   "type": "timeseries",
   "description": "Total number of bytes compacted since server [re]start.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_compaction_bytescompacted_count{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "timeseries",
   "description": "Estimated number of compactions remaining to perform.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_compaction_pendingtasks{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "timeseries",
   "description": "Number of completed compactions since server [re]start.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(instance) (cassandra_compaction_completedtasks{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Compactions Completed",
   "type": "timeseries",
   "description": "Throughput of completed compactions since server [re]start.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_compaction_totalcompactionscompleted_count{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Tasks By Table Name",
   "type": "timeseries",
   "description": "Estimated number of compactions remaining to perform, grouped by keyspace and then table name. This info is also kept in Table Metrics",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_pendingcompactions{instance=~\"$instance\", table!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}