{
 "title": "SSTable Index Metrics",
 "description": "https://cassandra.apache.org/doc/4.1/cassandra/operating/metrics.html#sstable-index-metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cassandra_index_indexedentrysize,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Indexed Entry Size",
   "type": "timeseries",
   "description": "Histogram of the on-heap size, in bytes, of the index across all SSTables.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(index) (cassandra_index_indexedentrysize{instance=~\"$instance\", quantile=\"0.99\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Info Count",
   "type": "timeseries",
   "description": "Histogram of the number of on-heap index entries managed across all SSTables.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by(index) (cassandra_index_indexinfocount{instance=~\"$instance\", quantile=\"0.99\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Info Gets",
   "type": "timeseries",
   "description": "Histogram of the number index seeks performed per SSTable.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(index) (cassandra_index_indexinfogets{instance=~\"$instance\", quantile=\"0.99\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}