{
 "title": "Storage Metrics",
 "description": "https://cassandra.apache.org/doc/4.1/cassandra/operating/metrics.html#storage-metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cassandra_storage_load_count,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Storage Exceptions",
   "type": "timeseries",
   "description": "Number of internal exceptions caught. Under normal exceptions this should be zero.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_storage_exceptions_count{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Count (Bytes)",
   "type": "timeseries",
   "description": "Size, in bytes, of the on disk data size this node manages.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_storage_load_count{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Hints",
   "type": "timeseries",
   "description": "Number of hint messages written to this node since [re]start. Includes one entry for each host to be hinted per hint.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_storage_totalhints_count{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Hints In Progress",
   "type": "timeseries",
   "description": "Number of hints attempting to be sent currently.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_storage_totalhintsinprogress_count{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}