{
 "title": "Table Metrics - Repair",
 "description": "https://cassandra.apache.org/doc/stable/cassandra/operating/metrics.html#table-metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cassandra_table_pendingcompactions,instance)"
    }
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": {
     "query": "label_values(cassandra_table_pendingcompactions,keyspace)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values(cassandra_table_pendingcompactions,table)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Percent Repaired",
   "type": "timeseries",
   "description": "Percent of table data that is repaired on disk.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_percentrepaired{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Repaired",
   "type": "timeseries",
   "description": "Size of table data repaired on disk",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_bytesrepaired{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Unrepaired",
   "type": "timeseries",
   "description": "Size of table data unrepaired on disk",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_bytesunrepaired{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Pending Repair",
   "type": "timeseries",
   "description": "Size of table data isolated for an ongoing incremental repair",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_bytespendingrepair{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anticompaction Time",
   "type": "timeseries",
   "description": "Time spent anticompacting before a consistent repair.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_anticompactiontime{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validation Time",
   "type": "timeseries",
   "description": "Time spent doing validation compaction during repair.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_validationtime{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Time",
   "type": "timeseries",
   "description": "Time spent doing streaming during repair.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_repairsynctime{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}