{
 "title": "Table Metrics - SSTable & Disk Space",
 "description": "https://cassandra.apache.org/doc/stable/cassandra/operating/metrics.html#table-metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cassandra_table_pendingcompactions,instance)"
    }
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": {
     "query": "label_values(cassandra_table_pendingcompactions,keyspace)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values(cassandra_table_pendingcompactions,table)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Compression Ratio",
   "type": "timeseries",
   "description": "Current compression ratio for all SSTables.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_compressionratio{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Compactions",
   "type": "timeseries",
   "description": "Estimate of number of pending compactions for this table.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_pendingcompactions{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compaction Bytes Written",
   "type": "timeseries",
   "description": "Total number of bytes written by compaction since server [re]start.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_compactionbyteswritten_count{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live SSTable Count",
   "type": "timeseries",
   "description": "Number of SSTables on disk for this table.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_livesstablecount{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Disk Space Used",
   "type": "timeseries",
   "description": "Disk space used by SSTables belonging to this table (in bytes).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_livediskspaceused_count{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Disk Space Used",
   "type": "timeseries",
   "description": "Total disk space used by SSTables belonging to this table, including obsolete ones waiting to be GC’d.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_totaldiskspaceused_count{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}