{
 "title": "Table Metrics - Latencies",
 "description": "https://cassandra.apache.org/doc/stable/cassandra/operating/metrics.html#table-metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cassandra_table_readlatency_seconds,instance)"
    }
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": {
     "query": "label_values(cassandra_table_readlatency_seconds,keyspace)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values(cassandra_table_readlatency_seconds,table)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Local Read Latencies (seconds)",
   "type": "timeseries",
   "description": "Local read latency for this table.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_readlatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local Write Latencies (seconds)",
   "type": "timeseries",
   "description": "Local write latency for this table.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_writelatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local Range Latencies (seconds)",
   "type": "timeseries",
   "description": "Local range scan latency for this table.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_rangelatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coordinator Read Latencies (seconds)",
   "type": "timeseries",
   "description": "Coordinator read latency for this table.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_coordinatorreadlatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coordinator Write Latencies (seconds)",
   "type": "timeseries",
   "description": "Coordinator write latency for this table.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_coordinatorwritelatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coordinator Range Scan Latencies (seconds)",
   "type": "timeseries",
   "description": "Coordinator  range scan latency for this table.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_coordinatorscanlatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cas Prepare Latencies (seconds)",
   "type": "timeseries",
   "description": "Latency of paxos prepare round.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_caspreparelatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cas Propose Latencies (seconds)",
   "type": "timeseries",
   "description": "Latency of paxos propose round.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_casproposelatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cas Commit Latencies (seconds)",
   "type": "timeseries",
   "description": "Latency of paxos commit round.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_cascommitlatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}