{
 "title": "Table Stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_runtime_info,instance)"
    }
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": {
     "query": "label_values(cassandra_table_additionalwritelatencynanos,keyspace)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values(cassandra_table_additionalwritelatencynanos,table)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Write Latencies (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(quantile) (cassandra_table_writelatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\", quantile=\"0.99\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(quantile) (cassandra_table_writelatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\", quantile=\"0.75\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Latencies (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by(quantile) (cassandra_table_readlatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\", quantile=\"0.99\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(quantile) (cassandra_table_readlatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\", quantile=\"0.75\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cas Latencies (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max by(commit) (label_replace(cassandra_table_cascommitlatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\", quantile=\"0.99\"}, \"commit\", \"commit_P99\", \"quantile\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(commit) (label_replace(cassandra_table_cascommitlatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\", quantile=\"0.75\"}, \"commit\", \"commit_P75\", \"quantile\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(prepare) (label_replace(cassandra_table_caspreparelatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\", quantile=\"0.99\"}, \"prepare\", \"prepare_P99\", \"quantile\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(prepare) (label_replace(cassandra_table_caspreparelatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\", quantile=\"0.75\"}, \"prepare\", \"prepare_P75\", \"quantile\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(propose) (label_replace(cassandra_table_casproposelatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\", quantile=\"0.99\"}, \"propose\", \"propose_P99\", \"quantile\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(propose) (label_replace(cassandra_table_casproposelatency_seconds{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\", quantile=\"0.75\"}, \"propose\", \"propose_P75\", \"quantile\", \"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}