{
 "title": "Table Metrics - Memtables",
 "description": "https://cassandra.apache.org/doc/stable/cassandra/operating/metrics.html#table-metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cassandra_keyspace_allmemtableslivedatasize,instance)"
    }
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": {
     "query": "label_values(cassandra_table_memtableoffheapsize,keyspace)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values(cassandra_table_memtableonheapsize,table)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pending Flushes",
   "type": "timeseries",
   "description": "Estimated number of flush tasks pending for this table.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(instance) (cassandra_table_pendingflushes{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memtable Live Data Size",
   "type": "timeseries",
   "description": "Total amount of live data stored in the memtable, excluding any data structure overhead.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_memtablelivedatasize{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memtable OnHeap Size",
   "type": "timeseries",
   "description": "Total amount of data stored in the memtable that resides on-heap, including column related overhead and partitions overwritten.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_memtableonheapsize{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memtable OffHeap Size",
   "type": "timeseries",
   "description": "Total amount of data stored in the memtable that resides off-heap, including column related overhead and partitions overwritten.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "max by(table) (cassandra_table_memtableoffheapsize{instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}