{
 "title": "ThreadPool Metrics",
 "description": "https://cassandra.apache.org/doc/4.1/cassandra/operating/metrics.html",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cassandra_threadpools_activetasks,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Tasks",
   "type": "timeseries",
   "description": "Number of tasks being actively worked on by this pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(threadpools) (cassandra_threadpools_activetasks{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "timeseries",
   "description": "Number of queued tasks queued up on this pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by(threadpools) (cassandra_threadpools_pendingtasks{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "timeseries",
   "description": "Number of tasks completed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(threadpools) (cassandra_threadpools_completedtasks{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Blocked Tasks",
   "type": "timeseries",
   "description": "Number of tasks that were blocked due to queue saturation.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by(threadpools) (cassandra_threadpools_totalblockedtasks_count{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Currently Blocked Tasks",
   "type": "timeseries",
   "description": "Number of tasks that are currently blocked due to queue saturation but on retry will become unblocked.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by(threadpools) (cassandra_threadpools_currentlyblockedtasks_count{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Pool Size",
   "type": "timeseries",
   "description": "The maximum number of threads in this pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max by(threadpools) (cassandra_threadpools_maxpoolsize{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Tasks Queued",
   "type": "timeseries",
   "description": "The maximum number of tasks queued before a task get blocked.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "max by(threadpools) (cassandra_threadpools_maxtasksqueued{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}