global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "jmx_prometheus"
    honor_labels: true
    file_sd_configs:
      - files:
          - "tg_jmx_prometheus.json"
  - job_name: "reaper"
    honor_labels: true
    metrics_path: /prometheusMetrics
    file_sd_configs:
      - files:
          - "tg_reaper.json"
